// Generated by gencpp from file chessbot/ChessImageRequest.msg
// DO NOT EDIT!


#ifndef CHESSBOT_MESSAGE_CHESSIMAGEREQUEST_H
#define CHESSBOT_MESSAGE_CHESSIMAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chessbot
{
template <class ContainerAllocator>
struct ChessImageRequest_
{
  typedef ChessImageRequest_<ContainerAllocator> Type;

  ChessImageRequest_()
    {
    }
  ChessImageRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::chessbot::ChessImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chessbot::ChessImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChessImageRequest_

typedef ::chessbot::ChessImageRequest_<std::allocator<void> > ChessImageRequest;

typedef boost::shared_ptr< ::chessbot::ChessImageRequest > ChessImageRequestPtr;
typedef boost::shared_ptr< ::chessbot::ChessImageRequest const> ChessImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chessbot::ChessImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chessbot::ChessImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace chessbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chessbot::ChessImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chessbot::ChessImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chessbot::ChessImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chessbot::ChessImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chessbot::ChessImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chessbot::ChessImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chessbot::ChessImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::chessbot::ChessImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::chessbot::ChessImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chessbot/ChessImageRequest";
  }

  static const char* value(const ::chessbot::ChessImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chessbot::ChessImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::chessbot::ChessImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chessbot::ChessImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChessImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chessbot::ChessImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::chessbot::ChessImageRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CHESSBOT_MESSAGE_CHESSIMAGEREQUEST_H
