// Generated by gencpp from file chessbot/ChessImage.msg
// DO NOT EDIT!


#ifndef CHESSBOT_MESSAGE_CHESSIMAGE_H
#define CHESSBOT_MESSAGE_CHESSIMAGE_H

#include <ros/service_traits.h>


#include <chessbot/ChessImageRequest.h>
#include <chessbot/ChessImageResponse.h>


namespace chessbot
{

struct ChessImage
{

typedef ChessImageRequest Request;
typedef ChessImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChessImage
} // namespace chessbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chessbot::ChessImage > {
  static const char* value()
  {
    return "0f2a2d0ca79f98f8355432897b5e5ec2";
  }

  static const char* value(const ::chessbot::ChessImage&) { return value(); }
};

template<>
struct DataType< ::chessbot::ChessImage > {
  static const char* value()
  {
    return "chessbot/ChessImage";
  }

  static const char* value(const ::chessbot::ChessImage&) { return value(); }
};


// service_traits::MD5Sum< ::chessbot::ChessImageRequest> should match
// service_traits::MD5Sum< ::chessbot::ChessImage >
template<>
struct MD5Sum< ::chessbot::ChessImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chessbot::ChessImage >::value();
  }
  static const char* value(const ::chessbot::ChessImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chessbot::ChessImageRequest> should match
// service_traits::DataType< ::chessbot::ChessImage >
template<>
struct DataType< ::chessbot::ChessImageRequest>
{
  static const char* value()
  {
    return DataType< ::chessbot::ChessImage >::value();
  }
  static const char* value(const ::chessbot::ChessImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chessbot::ChessImageResponse> should match
// service_traits::MD5Sum< ::chessbot::ChessImage >
template<>
struct MD5Sum< ::chessbot::ChessImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chessbot::ChessImage >::value();
  }
  static const char* value(const ::chessbot::ChessImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chessbot::ChessImageResponse> should match
// service_traits::DataType< ::chessbot::ChessImage >
template<>
struct DataType< ::chessbot::ChessImageResponse>
{
  static const char* value()
  {
    return DataType< ::chessbot::ChessImage >::value();
  }
  static const char* value(const ::chessbot::ChessImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHESSBOT_MESSAGE_CHESSIMAGE_H
